### ISSUE TITLE
Incorrect no of rows displayed

### ISSUE THREAD

**Issue by DoctorsDad** [Epstone/Simple-MVC-User-Management#3]
Hi, Nice work. I like but I don't understand it all yet.

I altered user-table-area.html as follows:
        <select class="pagesize">
            <option selected="selected" value="5">5</option>
            <option value="10">10</option>
            <option value="20">20</option>
and it correctly displays 5 rows instead of 10 but the legend still displays '1 to 10 of 500 rows'.

I think the issue is somewhere in the javascript but I've no idea how to track it down further.

If you could point me to an idiots guide to debugging this technology, I'd be happy to do the leg-work.

Regards,
Dave.

**Comment by DoctorsDad** [comment]
Further to this, the incorrect number is only displayed initally - once any of the navigation buttons are clicked it is corrected.

**Comment by Epstone** [comment]
Hi Dave,
to change the initial number of rows shown you have to change the numbers in https://github.com/Epstone/Simple-MVC-User-Management/blob/master/SimpleMvcUserManagement/Scripts/user-table-area.html#L40
like your allready did.
And also the https://github.com/Epstone/Simple-MVC-User-Management/blob/master/SimpleMvcUserManagement/Scripts/simple-user-management.js#L36

There just add a ,size: 5 object property for 5 rows to be shown at first.
Then recompile.
For more tablesorter settings have a look at the tablesorter js file:
https://github.com/Epstone/Simple-MVC-User-Management/blob/master/SimpleMvcUserManagement/Scripts/tablesorter-pager.js#L199

Br Epstone

**Comment by DoctorsDad** [comment]
Excellent – thank you!

Can you recommend a source of info on how to debug these projects that have components in various languages?

I’m an old hand in standard Windows apps but new to the web.

For example, in one project the ManageRoles pop up dialogue refuses to show whereas in a test app it works fine.

My problem is that I can’t see how to trace the problem to its source.

Regards,

Dave.

**Comment by Epstone** [comment]
This project is not the best start for debugging JavaScript because the scripts are included through the ressource file and you would have to recompile all the time when you change the js code.

I prefer Google Chromes builtin web developer tools (just hit F12) and there I would recommend you to look for errors in the console section. Also use the console.debug(" some string "); in the javascript or just type debugger; to get a manual break point. 
Little more info: http://www.youtube.com/watch?v=c_oiQYirKuY&feature=player_embedded
br
